title: sl_拾柒
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/cyclone.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: sl_拾柒 # add your name
author-img: sl17.png # add your photo
about-author: 当你的生命里出现了生老病死这种事，你就会发现从前夜里的忧伤就是个屁。 # add description
social-qq: 2581005673 # add your Twitter handle
social-comments: p_q777 # add your Facebook handle
social-github: sl17 # add your Github handle
social-linkedin:  # add your linkedin handle
social-email: leijc_work@163.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

excerpt_separator: '\n\n\n\n'

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
